version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:
  
services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: bananny747/foodgram_backend
    volumes:
      - static_value:/backend_static
      - media_value:/media
    depends_on:
      - db
    env_file:
      - ../.env
    restart: always

  frontend:
    image: bananny747/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_value:/static
    depends_on:
      - db

  nginx:
    image: bananny747/foodgram_nginx
    depends_on:
      - backend
    env_file:
      - ../.env
    ports:
      - "8001:80"
    volumes:
      - static_value:/static
      - media_value:/media
