# Generated by Django 3.2.3 on 2023-07-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Аутентифицированный пользователь'), ('admin', 'Администратор')], default='user', max_length=16),
        ),
    ]
